In [48]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(123)

expected_action_value  = np.random.uniform(0 ,1 , 10)
expected_action_value = expected_action_value/expected_action_value.sum()
num_epoch = 10000
alpha = 0.2
beta  = 0.8
print(expected_action_value)

[0.12798052 0.05257987 0.04168536 0.1013075  0.13220688 0.07774843
 0.18022149 0.1258417  0.08837421 0.07205402]


In [49]:
# Linear Reward Inaction 
estimated = np.zeros(10)+0.1
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.3 else np.random.choice(10, p=estimated)
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1

    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
    else:
        estimated = (mask) * ((1-beta)*estimated) + (1-mask) * (beta/9.0 + (1-beta)*estimated)

print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))
print(estimated.sum())

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.111 0.11  0.111 0.111 0.095 0.107 0.111 0.111 0.111 0.022]
[1026.  961.  947.  994. 1030.  978. 1092. 1026.  971.  975.]
0.9999999999999999


In [52]:
# Linear Reward Inaction 
alpha = 0.00001
estimated = np.zeros(10)+0.1
pull_count= np.zeros(10)

for iter in range(num_epoch):
    
    current_choice = np.argmax(estimated) if np.random.uniform(0,1) > 0.9 else np.random.choice(10, p=estimated)
    pull_count[current_choice] = pull_count[current_choice] + 1
    current_reward = 1 if expected_action_value[current_choice]>np.random.uniform(0,1) else 0
    
    mask = np.zeros(10) 
    mask[current_choice] = 1
    
    if current_reward == 1:
        estimated = (mask) * (estimated + alpha*(1-estimated)) + (1-mask) * ((1-alpha) *estimated)
        
    estimated = estimated/estimated.sum()
        
print(np.around(expected_action_value,3))
print(np.around(estimated,3))
print(np.around(pull_count,3))
print(estimated.sum())

[0.128 0.053 0.042 0.101 0.132 0.078 0.18  0.126 0.088 0.072]
[0.1   0.1   0.099 0.1   0.1   0.1   0.102 0.1   0.1   0.1  ]
[ 879.  949.  914.  970.  953.  916. 1732.  933.  879.  875.]
1.0


In [8]:
import random, datetime, numpy as np, math
random.seed(datetime.datetime.now())

def lrI(alpha):
	print("\n\nStarting LRI - Linear Reward Inaction Algorithm\n\n")
	for j in range(1):
		levers = ["q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10"]
		reward_percent = [random.random() for i in range(10)]
		lever_count, reward_count  = ([0 for i in range(10)] for i in range(2))
		#probability of choosing a lever - sum equal to 1
		lever_probability = [0.1 for i in range(10)]
		optimal_decision = 0
		#randomly choose a lever and set alpha/beta values
		lever = random.randint(0, 9)
		beta = 0
		#gets lever that is the most optimal (has the highest chance of giving us a reward)
		optimal_decision =reward_percent.index(max(reward_percent))
		i = 1
		while i <= 10000:
		# if reward = 1
			if random.random() < reward_percent[lever]:
				reward_count[lever]+=1
				#update the current lever
				lever_probability[lever] = lever_probability[lever] + alpha * (1- lever_probability[lever])
				#update other levers
				for x in range(0, len(lever_probability)):
					if x is not lever:
						lever_probability[x] = (1 - alpha) * lever_probability[x]
			lever_count[lever] += 1
			i+=1
			#choose the lever according to the probability distribution lever_probability
			lever = np.random.choice(10, p=lever_probability)

		print("Run: %d, Optimal Decision: %s with chance: %f chosen %d times. Average reward: %.2f" % (j+1, levers[optimal_decision], reward_percent[optimal_decision], lever_count[optimal_decision], sum(reward_count)/i))
		print(np.around(reward_percent,3),sum(reward_percent))
		print(np.around(lever_probability,3),sum(lever_probability))
		print(np.around(np.array(lever_probability)*sum(reward_percent),3))
		print(lever_count)
        
def lrI2(alpha):
    print("\n\nStarting LRI - Linear Reward Inaction Algorithm\n\n")
    for j in range(1):
        levers = ["q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10"]
        reward_percent = [random.random() for i in range(10)]
        lever_count, reward_count  = ([0 for i in range(10)] for i in range(2))
        lever_probability = np.zeros(10) + 0.1
        optimal_decision = 0
        lever = random.randint(0, 9)
        optimal_decision = reward_percent.index(max(reward_percent))
        i = 1
        while i <= 10000:
            if random.random() < reward_percent[lever]:
                reward_count[lever] = reward_count[lever] + 1
                mask = np.zeros(10)
                mask[lever] = mask[lever] + 1
                lever_probability = (mask) * (lever_probability + alpha*(1-lever_probability)) + (1-mask) *((1 - alpha) * lever_probability)

            lever_count[lever] += 1; i+=1
            lever = np.random.choice(10, p=lever_probability)

        print("Run: %d, Optimal Decision: %s with chance: %f chosen %d times / 10000"% 
              (j+1, levers[optimal_decision], reward_percent[optimal_decision], lever_count[optimal_decision])  )
        print(np.around(reward_percent,3),sum(reward_percent))
        print(np.around(lever_probability,3),lever_probability.sum())
        print(np.around(lever_probability*sum(reward_percent),3))
        print(lever_count)
        
alpha2 =  0.0001
lrI(alpha2)
lrI2(alpha2)



Starting LRI - Linear Reward Inaction Algorithm


Run: 1, Optimal Decision: q2 with chance: 0.780948 chosen 1182 times. Average reward: 0.41
[0.169 0.781 0.155 0.319 0.064 0.285 0.516 0.496 0.768 0.335] 3.8867135376668
[0.079 0.144 0.076 0.09  0.07  0.085 0.112 0.11  0.142 0.092] 1.0000000000000335
[0.308 0.561 0.294 0.349 0.273 0.331 0.434 0.426 0.553 0.358]
[924, 1182, 848, 935, 924, 856, 1070, 1111, 1174, 976]


Starting LRI - Linear Reward Inaction Algorithm


Run: 1, Optimal Decision: q6 with chance: 0.984267 chosen 1225 times / 10000
[0.95  0.362 0.217 0.685 0.401 0.984 0.843 0.836 0.393 0.347] 6.019174952512265
[0.134 0.076 0.064 0.103 0.08  0.143 0.119 0.128 0.079 0.075] 1.0000000000000464
[0.808 0.455 0.386 0.622 0.481 0.859 0.714 0.768 0.474 0.454]
[1150, 873, 776, 1032, 867, 1225, 1081, 1205, 892, 899]


In [93]:
import random, datetime, numpy as np, math
random.seed(datetime.datetime.now())

def lrI(alpha):
	print("\n\nStarting LRI - Linear Reward Inaction Algorithm\n\n")
	for j in range(1):
		levers = ["q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10"]
		reward_percent = np.random.beta(0.1,0.3,size=10)
		reward_percent = reward_percent/sum(reward_percent)
		lever_count, reward_count  = ([0 for i in range(10)] for i in range(2))
		#probability of choosing a lever - sum equal to 1
		lever_probability = [0.1 for i in range(10)]
		optimal_decision = 0
		#randomly choose a lever and set alpha/beta values
		lever = random.randint(0, 9)
		beta = 0
		#gets lever that is the most optimal (has the highest chance of giving us a reward)
		optimal_decision = np.argmax(reward_percent)
		i = 1
		while i <= 10000:
		# if reward = 1
			if random.random() < reward_percent[lever]:
				reward_count[lever]+=1
				#update the current lever
				lever_probability[lever] = lever_probability[lever] + alpha * (1- lever_probability[lever])
				#update other levers
				for x in range(0, len(lever_probability)):
					if x is not lever:
						lever_probability[x] = (1 - alpha) * lever_probability[x]
			lever_count[lever] += 1
			i+=1
			#choose the lever according to the probability distribution lever_probability
			lever = np.random.choice(10, p=lever_probability)

		print("Run: %d, Optimal Decision: %s with chance: %f chosen %d times. Average reward: %.2f" % (j+1, levers[optimal_decision], reward_percent[optimal_decision], lever_count[optimal_decision], sum(reward_count)/i))
		print(np.around(reward_percent,3))
		print(np.around(lever_probability,3))
		print(lever_count)
        
def lrI2(alpha):
    print("\n\nStarting LRI - Linear Reward Inaction Algorithm\n\n")
    for j in range(1):
        levers = ["q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10"]
        reward_percent = np.random.beta(0.1,0.3,size=10)
        reward_percent = reward_percent/reward_percent.sum()
        lever_count, reward_count  = ([0 for i in range(10)] for i in range(2))
        lever_probability = np.zeros(10) + 0.1
        optimal_decision = 0
        lever = random.randint(0, 9)
        optimal_decision = np.argmax(reward_percent)
        i = 1
        while i <= 10000:
            if random.random() < reward_percent[lever]:
                reward_count[lever] = reward_count[lever] + 1
                mask = np.zeros(10)
                mask[lever] = mask[lever] + 1
                lever_probability = (mask) * (lever_probability + alpha*(1-lever_probability)) + (1-mask) *((1 - alpha) * lever_probability)

            lever_count[lever] += 1; i+=1
            lever = np.random.choice(10, p=lever_probability)

        print("Run: %d, Optimal Decision: %s with chance: %f chosen %d times / 10000"% 
              (j+1, levers[optimal_decision], reward_percent[optimal_decision], lever_count[optimal_decision])  )
        print(np.around(reward_percent,3))
        print(np.around(lever_probability,3))
        print(lever_count)
        
alpha2 =  0.01
lrI(alpha2)
lrI2(alpha2)



Starting LRI - Linear Reward Inaction Algorithm


Run: 1, Optimal Decision: q1 with chance: 0.289948 chosen 4479 times. Average reward: 0.27
[0.29  0.284 0.179 0.    0.104 0.061 0.004 0.    0.078 0.   ]
[0.771 0.229 0.    0.    0.    0.    0.    0.    0.    0.   ]
[4479, 4634, 329, 69, 75, 101, 62, 81, 101, 69]


Starting LRI - Linear Reward Inaction Algorithm


Run: 1, Optimal Decision: q3 with chance: 0.394228 chosen 8565 times / 10000
[0.132 0.    0.394 0.    0.002 0.    0.119 0.    0.352 0.   ]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[120, 44, 8565, 40, 57, 51, 77, 49, 954, 43]


# Reference 
1. Michael Pacheco. (2019). Michaelpacheco.net. Retrieved 9 January 2019, from https://www.michaelpacheco.net/blog/RL-multi-armed-bandit-2
2. numpy.random.choice — NumPy v1.15 Manual. (2019). Docs.scipy.org. Retrieved 9 January 2019, from https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.choice.html

In [37]:
lever_probability = np.random.uniform(0,1,10)
lever_probability = lever_probability/lever_probability.sum()
print(np.random.choice(10, p=lever_probability))


0
7
