In [2]:
# import lib
import numpy as np 
import tensorflow as tf
import matplotlib.pyplot as plt

np.random.seed(78)
tf.set_random_seed(678)

In [35]:
# declare
num_epoch    = 10000
ground_truth = np.random.uniform(0,1,10)
expected     = np.zeros(10)
pull_count   = np.zeros(10) 
print(ground_truth)
print(expected)
print(pull_count)

[0.70466012 0.37603232 0.00821394 0.7227668  0.13360218 0.72017615
 0.0925883  0.81947774 0.02255412 0.89319985]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [67]:
# train 
num_epoch = 100000
for iter in range(num_epoch):
    current_action = np.random.randint(10)
    pull_count[current_action] = pull_count[current_action] + 1
    if np.random.uniform(0,1) < ground_truth[current_action]: current_reward = 1
    else: current_reward = 0
    expected[current_action] = expected[current_action] + (1/pull_count[current_action]) * (current_reward-expected[current_action])
    
print(np.around(ground_truth,3))
print(np.around(expected,3))
print(np.around(pull_count,3))

[0.705 0.376 0.008 0.723 0.134 0.72  0.093 0.819 0.023 0.893]
[0.704 0.377 0.008 0.723 0.133 0.72  0.092 0.82  0.023 0.893]
[518188. 518036. 518652. 518774. 518253. 517673. 517707. 519307. 518760.
 518182.]


In [77]:
# declare
import multiprocessing

num_epoch    = 100000
ground_truth = np.random.uniform(0,1,10)
expected     = np.zeros(10)
pull_count   = np.zeros(10) 
print(ground_truth)
print(expected)
print(pull_count)

[0.23402911 0.05549349 0.23618227 0.37087525 0.12508529 0.19603261
 0.82944963 0.00266729 0.52289777 0.67353721]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [84]:
# train 
def findvalue():
    global expected,pull_count
    current_action = np.random.randint(10)
    pull_count[current_action] = pull_count[current_action] + 1
    if np.random.uniform(0,1) < ground_truth[current_action]: current_reward = 1
    else: current_reward = 0
    expected[current_action] = expected[current_action] + (1/pull_count[current_action]) * (current_reward-expected[current_action])
    
for iter in range(400):
    p = multiprocessing.Process(target=findvalue)
    p.start()
p.join()

global expected,pull_count
print(np.around(ground_truth,3))
print(np.around(expected,3))
print(np.around(pull_count,3))

[0.234 0.055 0.236 0.371 0.125 0.196 0.829 0.003 0.523 0.674]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [91]:
from threading import Thread

for iter in range(num_epoch):
   t = Thread(target=findvalue)
   t.start()
t.join()

print(np.around(ground_truth,3))
print(np.around(expected,3))
print(np.around(pull_count,3))

[0.234 0.055 0.236 0.371 0.125 0.196 0.829 0.003 0.523 0.674]
[0.229 0.055 0.234 0.363 0.117 0.198 0.829 0.002 0.525 0.671]
[ 9910. 10056. 10032. 10044.  9987.  9878. 10150. 10046.  9940. 10057.]


# Reference 
1. Solving the Multi-Armed Bandit Problem – Towards Data Science. (2017). Towards Data Science. Retrieved 24 December 2018, from https://towardsdatascience.com/solving-the-multi-armed-bandit-problem-b72de40db97c
2. 