In [1]:
# import lib
import numpy as np 
import tensorflow as tf
import matplotlib.pyplot as plt
import threading
np.random.seed(78)
tf.set_random_seed(678)

In [8]:
# declare
num_epoch    = 1000000
ground_truth = np.random.uniform(0,1,10)
expected     = np.zeros(10)
pull_count   = np.zeros(10) 
print(ground_truth)
print(expected)
print(pull_count)

[0.90626164 0.02255411 0.87551925 0.11565788 0.09965873 0.92431365
 0.88146685 0.12355341 0.18428255 0.04542723]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# train 
for iter in range(num_epoch):
    current_action = np.random.randint(10)
    pull_count[current_action] = pull_count[current_action] + 1
    if np.random.uniform(0,1) < ground_truth[current_action]: current_reward = 1
    else: current_reward = 0
    expected[current_action] = expected[current_action] + (1/pull_count[current_action]) * (current_reward-expected[current_action])
    
print(np.around(ground_truth,3))
print(np.around(expected,3))
print(np.around(pull_count,3))

[0.906 0.023 0.876 0.116 0.1   0.924 0.881 0.124 0.184 0.045]
[0.904 0.023 0.876 0.114 0.098 0.924 0.882 0.124 0.186 0.045]
[ 99894. 100048.  99708. 100042. 100219.  99885.  99606. 100124. 100277.
 100197.]


In [10]:
# multi threaded
expected     = np.zeros(10)
pull_count   = np.zeros(10) 
print(ground_truth)
print(expected)
print(pull_count)

def findvalue():
    global expected,pull_count
    for iter in range(num_epoch//2):
        current_action = np.random.randint(10)
        pull_count[current_action] = pull_count[current_action] + 1
        if np.random.uniform(0,1) < ground_truth[current_action]: current_reward = 1
        else: current_reward = 0
        expected[current_action] = expected[current_action] + (1/pull_count[current_action]) * (current_reward-expected[current_action])
  
jobs = []
for i in range(0, 2):
    thread = threading.Thread(target=findvalue())
    jobs.append(thread)

for x in jobs:
    x.start()

for x in jobs:
    x.join()

print(np.around(ground_truth,3))
print(np.around(expected,3))
print(np.around(pull_count,3))

[0.90626164 0.02255411 0.87551925 0.11565788 0.09965873 0.92431365
 0.88146685 0.12355341 0.18428255 0.04542723]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.906 0.023 0.876 0.116 0.1   0.924 0.881 0.124 0.184 0.045]
[0.906 0.022 0.875 0.115 0.099 0.922 0.882 0.124 0.184 0.045]
[ 99787. 100324. 100545.  99759.  99898.  99667.  99909. 100175. 100262.
  99674.]


# Reference 
1. Solving the Multi-Armed Bandit Problem – Towards Data Science. (2017). Towards Data Science. Retrieved 24 December 2018, from https://towardsdatascience.com/solving-the-multi-armed-bandit-problem-b72de40db97c
2. 